server:
  port: 8001
---
spring:
  profiles:
    active:
    - test
    
...
---
spring:
  config:
    activate:
      on-profile:
      - dev
db:
  driver-classname: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl11
  username: system
  password: pinku
  
...
---
spring:
  config:
    activate:
      on-profile:
      - test
db:
  driver-classname: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:test
  username: system
  password: system
...