---
server:
  port: 8761
spring:
  application:
    name: spring-ha-eurakaserver
  config:
    activate:
      on-profile:
      - discoveryserver1
eureka:
  instance:
    hostname: discoveryserver1.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://discoveryserver2.com:8762/eureka, http://discoveryserver3.com:8763/eureka
...
---
server:
  port: 8762
spring:
  application:
    name: spring-ha-eurakaserver
  config:
    activate:
      on-profile:
      - discoveryserver2
eureka:
  instance:
    hostname: discoveryserver2.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://discoveryserver3.com:8763/eureka, http://discoveryserver1.com:8761/eureka
...
---
server:
  port: 8763
spring:
  application:
    name: spring-ha-eurakaserver
  config:
    activate:
      on-profile:
      - discoveryserver3
eureka:
  instance:
    hostname: discoveryserver3.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://discoveryserver2.com:8762/eureka, http://discoveryserver1.com:8761/eureka
...
