server:
  port: 9903
  
spring:
  application:
    name: USER-CONSUMER-FEIGN-CLIENT
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
      
feign:
  client:
    config:
      default: 
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
                
